import { MetaMaskContextProvider } from '@/hooks/UseMetaMask'
import './globals.css'
import { GlobalContextProvider } from '@/hooks/store'
import Header from '@/components/Header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='dark'>
      <body>
        <MetaMaskContextProvider>
        <Header/>
        {children}
        </MetaMaskContextProvider>
      </body>
    </html>
  )
}
